services:
  accounts:
    image: "lokesh874/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank


  loans:
    image: "lokesh874/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank


  cards:
    image: "lokesh874/cards:s4"
    container_name: cards-ms
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank


networks:
  eazybank:
    driver: "bridge"